### ISSUE TITLE
wrong camera index

### ISSUE THREAD

**Issue by jonnytest1** [JohnHardy/pyusbcameraindex#1]
when i run the command it gives index 0 , but it only shows this device when i enter index "1" for capturing

![image](https://github.com/user-attachments/assets/d3d6fdad-481e-4726-b2bf-7d66c495c568)

**Comment by jonnytest1** [comment]
nevermind i think i forgot to use DSHOW

**Comment by JohnHardy** [comment]
Glad you sorted it! 👍

**Comment by jonnytest1** [comment]
oh PS :  this could use manual typing ^^
![image](https://github.com/user-attachments/assets/8abd830b-39d9-4733-98c5-684ed5e00945)
